export const ROUTES = {
  dashboard: "/dashboard",
  employees: "/employees",
  branches: "/branches",
  leads: "/leads",
  logs: "/logs",
  attendance: "/attendance",
  lateApprovals: "/attendance/late-approvals",
  lateHistory: "/attendance/late-history",
  dailyReport: "/daily-report",
  dailyReportHistory: "/daily-report/history",
  dailyReports: "/daily-reports",
  settings: "/settings",
  salary: "/salary",
  payoutNew: "/salary/payouts/new",
  payoutDetail: "/salary/payouts/:id",
} as const;
