import { PERMISSIONS, ROLES, type Permission, type Role } from "@/types/auth";
import { ROUTES } from "@/config/routes";

export interface SearchableItem {
  id: string;
  title: string;
  description?: string;
  category:
    "Navigation" | "Leads" | "Attendance" | "Leave" | "Dialer" | "Management";
  path: string;
  icon: string;
  keywords: string[];
  roles?: Role[];
  permissions?: Permission[];
}

export class SearchRegistry {
  static items: SearchableItem[] = [
    // Main Navigation
    {
      id: "nav-dashboard",
      title: "Dashboard",
      description: "Overview & Agent KPI stats",
      category: "Navigation",
      path: ROUTES.dashboard,
      icon: "dashboard",
      keywords: ["home", "main", "analytics", "overview"],
    },
    {
      id: "nav-tasks",
      title: "Tasks & To-Dos",
      description: "Manage personal and assigned tasks",
      category: "Navigation",
      path: "/tasks",
      icon: "check_circle",
      keywords: ["tasks", "todo", "assigned", "work"],
      permissions: [PERMISSIONS.TASK_VIEW],
    },
    {
      id: "nav-performance",
      title: "Performance",
      description: "Individual and team metrics",
      category: "Navigation",
      path: "/performance",
      icon: "show_chart",
      keywords: ["metrics", "kpi", "performance", "charts"],
      permissions: [PERMISSIONS.PERFORMANCE_VIEW],
    },
    {
      id: "nav-revenue",
      title: "Revenue Ledger",
      description: "Verified and pending revenue",
      category: "Navigation",
      path: "/revenue",
      icon: "payments",
      keywords: ["revenue", "money", "payments", "finance"],
      permissions: [PERMISSIONS.REVENUE_VIEW],
    },
    {
      id: "nav-contests",
      title: "Contests & Rewards",
      description: "Active competitions and achievements",
      category: "Navigation",
      path: "/contests",
      icon: "military_tech",
      keywords: ["contests", "competitions", "badges", "rewards"],
      permissions: [PERMISSIONS.CONTEST_VIEW_ALL],
    },

    // Leads & Actions
    {
      id: "leads-all",
      title: "All Leads",
      description: "View and search lead directory",
      category: "Leads",
      path: ROUTES.leads,
      icon: "group",
      keywords: ["leads", "contacts", "prospects", "all leads"],
      permissions: [PERMISSIONS.LEAD_VIEW],
    },
    {
      id: "leads-mine",
      title: "My Assigned Leads",
      description: "Leads specifically assigned to you",
      category: "Leads",
      path: `${ROUTES.leads}?view=mine`,
      icon: "person_search",
      keywords: ["my leads", "assigned leads", "mine"],
      roles: [ROLES.EMPLOYEE],
      permissions: [PERMISSIONS.LEAD_VIEW],
    },
    {
      id: "leads-followups",
      title: "Scheduled Follow-ups",
      description: "Pending calls and follow-up activities",
      category: "Leads",
      path: `${ROUTES.leads}?view=followups`,
      icon: "edit_calendar",
      keywords: ["followup", "schedule", "calls", "reminders"],
      roles: [ROLES.EMPLOYEE, ROLES.HEAD],
      permissions: [PERMISSIONS.LEAD_FOLLOWUP_VIEW],
    },
    {
      id: "leads-add",
      title: "Create New Lead",
      description: "Add a new lead to the CRM",
      category: "Leads",
      path: `${ROUTES.leads}?action=new`,
      icon: "person_add",
      keywords: ["add lead", "new lead", "create lead"],
      permissions: [PERMISSIONS.LEAD_CREATE],
    },

    // Dialer Module
    {
      id: "dialer-main",
      title: "Call Dialer Pad",
      description: "Initiate direct phone calls",
      category: "Dialer",
      path: "/dialer",
      icon: "call",
      keywords: ["dialer", "call", "phone", "dial"],
      roles: [ROLES.HEAD, ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
      permissions: [PERMISSIONS.CALL_INITIATE],
    },
    {
      id: "dialer-history",
      title: "Call Log History",
      description: "Review completed call records and recordings",
      category: "Dialer",
      path: "/dialer/history",
      icon: "history",
      keywords: ["call log", "call history", "recordings"],
      permissions: [PERMISSIONS.CALL_LOG_VIEW],
    },
    {
      id: "dialer-numbers",
      title: "Phone Numbers",
      description: "Manage Stringee phone lines",
      category: "Dialer",
      path: "/dialer/numbers",
      icon: "dialpad",
      keywords: ["numbers", "stringee", "phone lines"],
      permissions: [PERMISSIONS.STRINGEE_NUMBER_VIEW],
    },

    // Attendance Module
    {
      id: "attendance-my",
      title: "My Attendance Punch",
      description: "Clock in/out and view monthly log",
      category: "Attendance",
      path: ROUTES.attendance,
      icon: "calendar_today",
      keywords: ["attendance", "punch in", "clock in", "checkin"],
      roles: [ROLES.EMPLOYEE],
      permissions: [PERMISSIONS.ATTENDANCE_VIEW],
    },
    {
      id: "attendance-team",
      title: "Team Attendance",
      description: "Monitor team check-in statuses",
      category: "Attendance",
      path: "/attendance/team",
      icon: "groups",
      keywords: ["team attendance", "manager view", "checkins"],
      roles: [ROLES.MANAGER],
      permissions: [PERMISSIONS.ATTENDANCE_REPORT],
    },
    {
      id: "attendance-report",
      title: "Attendance Report",
      description: "Detailed organizational attendance audit",
      category: "Attendance",
      path: "/attendance/report",
      icon: "assessment",
      keywords: ["attendance report", "audit", "summary"],
      roles: [ROLES.HEAD, ROLES.ADMIN],
      permissions: [PERMISSIONS.ATTENDANCE_REPORT],
    },
    {
      id: "attendance-late-approvals",
      title: "Late Check-in Approvals",
      description: "Approve or reject late punch requests",
      category: "Attendance",
      path: "/attendance/late-approvals",
      icon: "fact_check",
      keywords: ["late approvals", "approve late", "late checkin"],
      permissions: [PERMISSIONS.LATE_CHECKIN_APPROVE],
    },
    {
      id: "attendance-late-history",
      title: "My Late Requests",
      description: "Review submitted late check-in requests",
      category: "Attendance",
      path: "/attendance/late-history",
      icon: "schedule",
      keywords: ["late history", "my late requests"],
      roles: [ROLES.EMPLOYEE],
      permissions: [PERMISSIONS.ATTENDANCE_VIEW],
    },

    // Leave Management
    {
      id: "leave-my",
      title: "My Leave Requests",
      description: "Apply for leaves and track request status",
      category: "Leave",
      path: "/leave",
      icon: "event_busy",
      keywords: ["apply leave", "time off", "vacation"],
      roles: [ROLES.EMPLOYEE],
      permissions: [PERMISSIONS.LEAVE_VIEW],
    },
    {
      id: "leave-approvals",
      title: "Leave Approvals",
      description: "Review team member leave requests",
      category: "Leave",
      path: "/leave/approvals",
      icon: "approval",
      keywords: ["leave approvals", "pending leaves"],
      roles: [ROLES.HEAD, ROLES.ADMIN, ROLES.MANAGER],
      permissions: [PERMISSIONS.LEAVE_APPROVE, PERMISSIONS.LEAVE_REJECT],
    },
    {
      id: "leave-balances",
      title: "Leave Balances",
      description: "View remaining entitlement balances",
      category: "Leave",
      path: "/leave/balances",
      icon: "account_balance_wallet",
      keywords: ["leave balance", "days left"],
      roles: [ROLES.ADMIN, ROLES.HEAD, ROLES.MANAGER, ROLES.EMPLOYEE],
      permissions: [PERMISSIONS.LEAVE_BALANCE_VIEW],
    },

    // System Administration
    {
      id: "sys-employees",
      title: "Employees Directory",
      description: "Manage employee profiles and roles",
      category: "Management",
      path: ROUTES.employees,
      icon: "badge",
      keywords: ["employees", "users", "staff", "team"],
      roles: [ROLES.HEAD, ROLES.ADMIN, ROLES.MANAGER],
      permissions: [PERMISSIONS.USER_VIEW],
    },
    {
      id: "sys-employees-add",
      title: "Add New Employee",
      description: "Create user credential & assign branch",
      category: "Management",
      path: `${ROUTES.employees}?action=new`,
      icon: "person_add",
      keywords: ["add employee", "create employee", "new staff"],
      roles: [ROLES.HEAD, ROLES.ADMIN, ROLES.MANAGER],
      permissions: [PERMISSIONS.USER_CREATE],
    },
    {
      id: "sys-branches",
      title: "Branch Management",
      description: "Manage office locations and branches",
      category: "Management",
      path: ROUTES.branches,
      icon: "domain",
      keywords: ["branches", "offices", "locations"],
      roles: [ROLES.HEAD, ROLES.ADMIN, ROLES.MANAGER],
      permissions: [PERMISSIONS.BRANCH_VIEW],
    },
    {
      id: "sys-logs",
      title: "Audit & System Logs",
      description: "System security and activity audit logs",
      category: "Management",
      path: ROUTES.logs,
      icon: "timer",
      keywords: ["logs", "audit", "system logs", "history"],
      roles: [ROLES.HEAD, ROLES.ADMIN, ROLES.MANAGER],
      permissions: [PERMISSIONS.AUDIT_VIEW],
    },
  ];
}
